myugctracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users.views import registration_view, login_view
from user_profile.views import upload_avatar
from company_service.views import edit_company, search_view
from company_service import views
from user_profile.views import user_profile
import home_page.urls
from user_profile import views as user_profile_views

urlpatterns = [
    path('home/', include(home_page.urls)),
    path('add_to_my_company/', views.add_to_my_company, name='add_to_my_company'),
    path('user_profile/', include('user_profile.urls')),
    path('edit_profile/', user_profile_views.edit_profile, name='edit_profile'),
    path('search/', views.search_view, name='search_results'),
    path('search/', search_view, name='search'),
    path('delete_from_profile/', views.delete_from_profile, name='delete_from_profile'),
    path('edit_company/<int:company_id>/', edit_company, name='edit_company'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('upload_avatar/', upload_avatar, name='upload_avatar'),
    path('add_company/', views.add_company_view, name='add_company'),
    path('profile/add_company/', views.add_company_view, name='add_company_view'),
    path('', registration_view, name='home'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('profile/', user_profile, name='user_profile'),
    path('login/', login_view, name='login'),
    path('register/', registration_view, name='register'),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/urls.py
# user_profile/urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('edit_profile_company/<int:profile_company_id>/', views.edit_profile_company, name='edit_profile_company'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('save_goal/', views.save_goal, name='save_goal'),
]

users/urls.py
# users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.registration_view, name='register'),
    path('login/', views.login_view, name='login'),
]


company_service/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.http import JsonResponse


class Company(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='companies')
    logo = models.ImageField(upload_to='logos/', null=True, blank=True)
    name = models.CharField(max_length=100)
    info = models.TextField()
    website = models.URLField(max_length=255, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    contact_person = models.CharField(max_length=100, default='manager')

    NICHE_CHOICES = [
        ('EC', 'Electronics & Computers'),
        ('FU', 'Furniture'),
        ('HP', 'Home Products'),
        ('CS', 'Cosmetics, skin & hair care'),
        ('TC', 'Toys and products for children'),
        ('CL', 'Clothes and shoes'),
        ('SH', 'Sports and hobbies'),
        ('FD', 'Food and drink'),
        ('OT', 'Others')
    ]

    CONTACTED_VIA_CHOICES = [
        ('NC', 'Email'),
        ('DI', 'Instagram'),
        ('CC', 'TikTok'),
        ('RE', 'Other')
    ]

    COLLABORATION_STATUS_CHOICES = [
        ('NC', 'Not contacted'),
        ('DI', 'In discussion'),
        ('CC', 'The deal is closed'),
        ('RE', 'Rejection')
    ]

    contacted_via = models.CharField(max_length=2, choices=CONTACTED_VIA_CHOICES, default='OT')
    collaboration_status = models.CharField(max_length=2, choices=COLLABORATION_STATUS_CHOICES)
    deal_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    content_count = models.IntegerField(null=True, blank=True)
    niche = models.CharField(max_length=2, choices=NICHE_CHOICES, default='OT')

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    companies = models.ManyToManyField(Company, related_name='users')

    def __str__(self):
        return self.user.username


class CompanyRanker:
    def __init__(self, companies):
        self.companies = companies

    def sort_by_name(self):
        self.companies = self.companies.order_by('name')

    def sort_by_status(self):
        self.companies = self.companies.order_by('collaboration_status')

    def search_by_name(self, search_query):
        return self.companies.filter(name__icontains=search_query)

    def search_by_status(self, search_query):
        return self.companies.filter(collaboration_status__icontains=search_query)

    def search_by_niche(self, search_query):
        return self.companies.filter(niche__icontains=search_query)

    def clear_filters(self):
        return self.companies.all()


companies = Company.objects.all()
ranker = CompanyRanker(companies)

ranker.sort_by_name()
sorted_companies_by_name = ranker.companies  # Отсортированный QuerySet

ranker.sort_by_status()
sorted_companies_by_status = ranker.companies  # Отсортированный QuerySet

filtered_companies_by_name = ranker.search_by_name('A')  # Отфильтрованный QuerySet
filtered_companies_by_status = ranker.search_by_status('Not contacted')  # Отфильтрованный QuerySet
filtered_companies_by_niche = ranker.search_by_niche('Tech')  # Отфильтрованный QuerySet

all_companies = ranker.clear_filters()  # Все компании без фильтров


user_profile/models.py
from django.db import models
from django.contrib.auth.models import User
from company_service.models import Company


class Profile(models.Model):
    DEAL_GOALS = [
        ('3', '3 successfully closed deals'),
        ('5', '5 successfully closed deals'),
        ('7', '7 successfully closed deals'),
        ('10', '10 successfully closed deals'),
        ('15', '15 successfully closed deals'),
        ('25', '25 successfully closed deals'),
        ('50', '50 successfully closed deals'),
        ('75', '75 successfully closed deals'),
        ('100', '100 successfully closed deals'),
    ]
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)
    goal = models.CharField(max_length=3, choices=DEAL_GOALS, default='5')
    companies = models.ManyToManyField(Company, through='ProfileCompany', related_name='profiles')

    def __str__(self):
        return f'{self.user.username} Profile'


class ProfileCompany(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    deal_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    content_count = models.IntegerField(null=True, blank=True)
    custom_info = models.TextField(null=True, blank=True)

    COLLABORATION_STATUS_CHOICES = [
        ('NC', 'Not contacted'),
        ('DI', 'In discussion'),
        ('CC', 'The deal is closed'),
        ('RE', 'Rejection')
    ]
    collaboration_status = models.CharField(max_length=100, choices=COLLABORATION_STATUS_CHOICES, default='NC')

    def __str__(self):
        return f"{self.profile.user.username} - {self.company.name}"





user_profile/forms.py
from django import forms
from .models import Profile
from .models import ProfileCompany, Company


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar', 'goal']
        widgets = {
            'goal': forms.Select(choices=Profile.DEAL_GOALS),
        }


class ProfileCompanyForm(forms.ModelForm):
    company_name = forms.CharField()
    company_info = forms.CharField(widget=forms.Textarea)
    company_website = forms.URLField()
    company_email = forms.EmailField()
    company_contact_person = forms.CharField()
    company_contacted_via = forms.ChoiceField(choices=Company.CONTACTED_VIA_CHOICES)
    company_niche = forms.ChoiceField(choices=Company.NICHE_CHOICES)

    class Meta:
        model = ProfileCompany
        fields = ['collaboration_status', 'deal_amount', 'content_count', 'custom_info']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.company:
            self.fields['company_name'].initial = self.instance.company.name
            self.fields['company_info'].initial = self.instance.company.info
            self.fields['company_website'].initial = self.instance.company.website
            self.fields['company_email'].initial = self.instance.company.email
            self.fields['company_contact_person'].initial = self.instance.company.contact_person
            self.fields['company_contacted_via'].initial = self.instance.company.contacted_via
            self.fields['company_niche'].initial = self.instance.company.niche

    def save(self, commit=True):
        profile_company = super().save(commit=False)
        company = profile_company.company
        company.name = self.cleaned_data['company_name']
        company.info = self.cleaned_data['company_info']
        company.website = self.cleaned_data['company_website']
        company.email = self.cleaned_data['company_email']
        company.contact_person = self.cleaned_data['company_contact_person']
        company.contacted_via = self.cleaned_data['company_contacted_via']
        company.niche = self.cleaned_data['company_niche']
        company.save()
        if commit:
            profile_company.save()
        return profile_company


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar', 'goal']


class AvatarForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar']


user_profile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.files.storage import default_storage
from django.http import JsonResponse
from django.utils.text import slugify
from django.shortcuts import get_object_or_404
from .models import ProfileCompany, Profile
from .forms import ProfileForm
from company_service.models import Company
from company_service.models import CompanyRanker
from .forms import ProfileCompanyForm


@login_required
def edit_profile_company(request, profile_company_id):
    profile_company = get_object_or_404(ProfileCompany, id=profile_company_id, profile=request.user.profile)
    if request.method == 'POST':
        form = ProfileCompanyForm(request.POST, instance=profile_company)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
        else:
            return JsonResponse({'success': False, 'errors': form.errors}, status=400)
    return JsonResponse({'success': False, 'errors': 'Invalid request method'}, status=400)


@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return JsonResponse({
                'message': 'Profile updated successfully'
            })
        else:
            errors = form.errors.as_json()
            print('Form errors:', errors)
            return JsonResponse({'error': 'Form is not valid', 'details': errors}, status=400)
    else:
        print('Invalid request method:', request.method)
    return JsonResponse({'error': 'Invalid request'}, status=400)


@login_required
def delete_from_profile(request):
    if request.method == "POST":
        company_id = request.POST.get("company_id")
        profile_company = get_object_or_404(ProfileCompany, profile=request.user.profile, company_id=company_id)
        profile_company.delete()
        return JsonResponse({"message": "Company removed from profile successfully"})
    return JsonResponse({"error": "Invalid request method"}, status=400)


# Обработчик для сохранения цели
def save_goal(request):
    if request.method == 'POST':
        goal = request.POST.get('goal')
        if goal:
            profile = request.user.profile
            profile.goal = goal
            profile.save()
            return JsonResponse({'message': 'Goal updated successfully', 'goal': profile.get_goal_display()})
        return JsonResponse({'error': 'Goal not provided'}, status=400)
    return JsonResponse({'error': 'Invalid request'}, status=400)


@login_required
def user_profile(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    profile_companies = user.profile.profilecompany_set.all()

    # Подсчет количества компаний по каждому статусу
    status_counts = {
        'CC': profile_companies.filter(collaboration_status='CC').count(),
        'DI': profile_companies.filter(collaboration_status='DI').count(),
        'NC': profile_companies.filter(collaboration_status='NC').count(),
        'RE': profile_companies.filter(collaboration_status='RE').count()
    }

    context = {
        'user': user,
        'profile': profile,
        'profile_companies': profile_companies,
        'status_counts': status_counts,
        'collaboration_status_choices': ProfileCompany.COLLABORATION_STATUS_CHOICES,
    }
    return render(request, 'user_profile.html', context)


def profile_view(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect('user_profile')
    else:
        form = ProfileForm(instance=request.user.profile)
    return render(request, 'user_profile.html', {'form': form})


@login_required
def search_view(request):
    search_query = request.GET.get('q', '')
    user = request.user

    companies = Company.objects.filter(user=user)
    ranker = CompanyRanker(companies)

    search_results = {
        'by_name': ranker.search_by_name(search_query),
        'by_status': ranker.search_by_status(search_query),
        'by_niche': ranker.search_by_niche(search_query)
    }

    results_count = {
        'by_name': len(search_results['by_name']),
        'by_status': len(search_results['by_status']),
        'by_niche': len(search_results['by_niche'])
    }

    for result_type in search_results:
        for company in search_results[result_type]:
            company.status_slug = slugify(company.get_collaboration_status_display())

    return render(request, 'search_results.html', {
        'search_query': search_query,
        'search_results': search_results,
        'results_count': results_count
    })


def upload_avatar(request):
    if request.method == 'POST' and request.FILES.get('avatar'):
        # Получить загруженное изображение
        uploaded_avatar = request.FILES['avatar']

        # Сохранить изображение на сервере
        file_path = default_storage.save('avatars/' + uploaded_avatar.name, uploaded_avatar)

        # Обновить профиль пользователя
        request.user.profile.avatar = file_path
        request.user.profile.save()

        return redirect('user_profile')
    else:
        return JsonResponse({'error': 'Invalid request'}, status=400)


templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <!-- Подключаем стили -->
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/home_page.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar">
        <a href="{% url 'home_page' %}" class="home-link">Home</a>
        <a href="{% url 'user_profile' %}" class="profile-link">Profile</a>
        <a href="{% url 'add_company' %}" class="add-company-link">Add Company</a>
        <form method="post" action="{% url 'logout' %}" style="display:inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-link" style="color: inherit; text-decoration: none;">Logout</button>
        </form>
    </nav>
    <div class="container">
        <h2>All Companies</h2>
        <div class="search-and-calculator">
            <form method="get" action="{% url 'home_page' %}">
                {{ form.as_p }}
                <button type="submit">Search</button>
            </form>
            <div class="calculator-container">
                <h2>Deal Calculator</h2>
                <form method="post">
                    {% csrf_token %}
                    <div>
                        {{ calculator_form.price_per_unit.label_tag }} {{ calculator_form.price_per_unit }}
                        {{ calculator_form.currency }}
                    </div>
                    <div>
                        {{ calculator_form.target_amount.label_tag }} {{ calculator_form.target_amount }}
                    </div>
                    <button type="submit" class="btn btn-primary">Calculate</button>
                </form>
                {% if result %}
                    <div class="result">
                        <p>Required number of content units: {{ result }}</p>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="companies-container">
            {% for company in companies %}
                <div class="card">
                    {% if company.logo %}
                        <img src="{{ company.logo.url }}" class="card-img-top" alt="{{ company.name }}">
                    {% else %}
                        <img src="{% static 'channels4_profile.png' %}" class="card-img-top" alt="Default Logo">
                    {% endif %}
                    <div class="card-body">
                        <h3 class="card-title">{{ company.name }}</h3>
                        <hr>
                        <p class="card-text"><strong>Contact Person:</strong> {{ company.contact_person }}</p>
                        <hr>
                        <p class="card-text"><strong>Website:</strong> <a href="{{ company.website }}">{{ company.website }}</a></p>
                        <hr>
                        <p class="card-text"><strong>Email:</strong> <a href="mailto:{{ company.email }}">{{ company.email }}</a></p>
                        <hr>
                        <p class="card-text"><strong>Description:</strong> {{ company.info }}</p>
                        <hr>
                        <p class="card-text"><strong>Niche:</strong> {{ company.get_niche_display }}</p>
                        <form method="post" action="{% url 'add_to_my_company' %}">
                            {% csrf_token %}
                            <button type="button" class="btn btn-primary add-to-my-company" data-company-id="{{ company.id }}">Add to my company</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <!-- Подключаем скрипты -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>








templates/search_results.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Results</title>
    <!-- Подключаем стили -->
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/search_results.css' %}">
    <link rel="stylesheet" href="{% static 'css/user_profile.css' %}">
</head>
<body>
    <nav class="navbar">
        <a href="{% url 'home_page' %}" class="home-link">Home</a>
        <a href="{% url 'user_profile' %}" class="profile-link">Profile</a>
        <a href="{% url 'add_company' %}" class="add-company-link">Add Company</a>
        <form action="{% url 'search' %}" method="get" class="search-form">
            <input type="text" name="q" placeholder="Search companies...">
            <button type="submit">Search</button>
        </form>
    </nav>
    <div class="container">
        <h2>Search Results for '{{ search_query }}'</h2>
        
        {% if results_count.by_name %}
            <h3>Results by Name ({{ results_count.by_name }} found)</h3>
            <div class="companies-container">
                {% for company in search_results.by_name %}
                    <div class="card">
                        {% if company.logo %}
                            <img src="{{ company.logo.url }}" class="card-img-top" alt="Company Logo">
                        {% endif %}
                        <div class="card-body">
                            <h3 class="card-title">{{ company.name }}</h3>
                            <hr>
                            <p class="card-text"><strong>Collaboration Status:</strong> 
                                <span class="status-label">
                                    {% if company.collaboration_status == "CC" %}
                                        <span style="color: green;">{{ company.get_collaboration_status_display }}</span>
                                    {% elif company.collaboration_status == "DI" %}
                                        <span style="color: orange;">{{ company.get_collaboration_status_display }}</span>
                                    {% elif company.collaboration_status == "NC" %}
                                        <span style="background: linear-gradient(to right, red, green); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">{{ company.get_collaboration_status_display }}</span>
                                    {% elif company.collaboration_status == "RE" %}
                                        <span style="color: red;">{{ company.get_collaboration_status_display }}</span>
                                    {% endif %}
                                </span>
                            </p>
                            <hr>
                            <p class="card-text"><strong>Niche:</strong> {{ company.get_niche_display }}</p>
                            <hr>
                            <p class="card-text"><strong>Contact Person:</strong> {{ company.contact_person }}</p>
                            <hr>
                            <p class="card-text"><strong>Website:</strong> <a href="{{ company.website }}">{{ company.website }}</a></p>
                            <hr>
                            <p class="card-text"><strong>Email:</strong> <a href="mailto:{{ company.email }}">{{ company.email }}</a></p>
                            <hr>
                            <p class="card-text"><strong>Description:</strong> {{ company.info }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>No companies with the name "{{ search_query }}" were found.</p>
        {% endif %}

        {% if results_count.by_status %}
            <h3>Results by Status ({{ results_count.by_status }} found)</h3>
            <div class="companies-container">
                {% for company in search_results.by_status %}
                    <div class="card">
                        {% if company.logo %}
                            <img src="{{ company.logo.url }}" class="card-img-top" alt="Company Logo">
                        {% endif %}
                        <div class="card-body">
                            <h3 class="card-title">{{ company.name }}</h3>
                            <hr>
                            <p class="card-text">
                                <strong>Collaboration Status:</strong> 
                                <span class="status-label 
                                    {% if company.collaboration_status == "CC" %}
                                        status-closed
                                    {% elif company.collaboration_status == "DI" %}
                                        status-discussion
                                    {% elif company.collaboration_status == "NC" %}
                                        status-not-contacted
                                    {% elif company.collaboration_status == "RE" %}
                                        status-rejection
                                    {% endif %}">
                                    {{ company.get_collaboration_status_display }}
                                </span>
                            </p>
                            <hr>
                            <p class="card-text"><strong>Niche:</strong> {{ company.get_niche_display }}</p>
                            <hr>
                            <p class="card-text"><strong>Contact Person:</strong> {{ company.contact_person }}</p>
                            <hr>
                            <p class="card-text"><strong>Website:</strong> <a href="{{ company.website }}">{{ company.website }}</a></p>
                            <hr>
                            <p class="card-text"><strong>Email:</strong> <a href="mailto:{{ company.email }}">{{ company.email }}</a></p>
                            <hr>
                            <p class="card-text"><strong>Description:</strong> {{ company.info }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>No companies with the status "{{ search_query }}" were found.</p>
        {% endif %}

        {% if results_count.by_niche %}
            <h3>Results by Niche ({{ results_count.by_niche }} found)</h3>
            <div class="companies-container">
                {% for company in search_results.by_niche %}
                    <div class="card">
                        {% if company.logo %}
                            <img src="{{ company.logo.url }}" class="card-img-top" alt="Company Logo">
                        {% endif %}
                        <div class="card-body">
                            <h3 class="card-title">{{ company.name }}</h3>
                            <hr>
                            <p class="card-text"><strong>Collaboration Status:</strong> 
                                <span class="status-label">
                                    {% if company.collaboration_status == "CC" %}
                                        <span style="color: green;">{{ company.get_collaboration_status_display }}</span>
                                    {% elif company.collaboration_status == "DI" %}
                                        <span style="color: orange;">{{ company.get_collaboration_status_display }}</span>
                                    {% elif company.collaboration_status == "NC" %}
                                        <span style="background: linear-gradient(to right, red, green); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">{{ company.get_collaboration_status_display }}</span>
                                    {% elif company.collaboration_status == "RE" %}
                                        <span style="color: red;">{{ company.get_collaboration_status_display }}</span>
                                    {% endif %}
                                </span>
                            </p>
                            <hr>
                            <p class="card-text"><strong>Niche:</strong> {{ company.get_niche_display }}</p>
                            <hr>
                            <p class="card-text"><strong>Contact Person:</strong> {{ company.contact_person }}</p>
                            <hr>
                            <p class="card-text"><strong>Website:</strong> <a href="{{ company.website }}">{{ company.website }}</a></p>
                            <hr>
                            <p class="card-text"><strong>Email:</strong> <a href="mailto:{{ company.email }}">{{ company.email }}</a></p>
                            <hr>
                            <p class="card-text"><strong>Description:</strong> {{ company.info }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>No companies with the niche "{{ search_query }}" were found.</p>
        {% endif %}
    </div>
    <!-- Подключаем скрипты -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>


